apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
    name: infisicalsecret-sample
    labels:
        label-to-be-passed-to-managed-secret: sample-value
    annotations:
        example.com/annotation-to-be-passed-to-managed-secret: "sample-value"
spec:
    hostAPI: https://app.infisical.com/api
    resyncInterval: 10
    authentication:
        # Native Kubernetes Auth
        kubernetesAuth:
          identityId: a6e100fc-c6c3-4ef4-a6fa-c466088f85fe
          serviceAccountRef:
            name: infisical-auth
            namespace: default

            # secretsScope is identical to the secrets scope in the universalAuth field in this sample.
            secretsScope:
                projectSlug: "example-project-3c-ms" # project settings -> copy project slug
                envSlug: dev
                secretsPath: "/"
                recursive: true

    managedSecretReference:
        secretName: managed-secret2
        secretNamespace: default
        creationPolicy: "Orphan" ## Owner | Orphan
        # secretType: kubernetes.io/dockerconfigjson




